version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /examples/echo
    schedule:
      interval: daily

  - package-ecosystem: bundler
    directory: /examples/echo
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /examples/sinatra
    schedule:
      interval: daily

  - package-ecosystem: bundler
    directory: /examples/sinatra
    schedule:
      interval: daily
